# IONOS Deploy Now Configuration for Static Angular App
---
version: 2

# Static site configuration (no Node.js runtime needed)
runtime: static

# No start command needed for static sites
# start: not needed for static

# No environment variables needed for static deployment
# env: not needed

# No build commands - files are already compiled
# build: not needed

# Static files configuration
static:
  folder: ./
